artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/shivakumar-ravichandran/ml-datasets/raw/refs/heads/main/NLP-Text-Summarizer/samsumdata.zip
  local_raw_folder: artifacts/data_ingestion/samsumdata.zip
  unzip_folder: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/validation_status.txt
  required_folders: ["train", "test", "validation"]